apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-gpu
spec:
  rayVersion: '2.10.0'
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray-ml:2.10.0
          resources:
            limits:
              cpu: 32
              memory: 120Gi
              nvidia.com/gpu: 2
            requests:
              cpu: 30
              memory: 100Gi
              nvidia.com/gpu: 2
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
